import { createStitches } from "@stitches/react";

export const {
  styled,
  css,
  globalCss,
  keyframes,
  getCssText,
  theme,
  createTheme,
  config,
} = createStitches({
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      inherit: "inherit",
      body: "#dddce5",
      white: "#FEFEFE",
      black: "#111316",
      grey10: "#FEFEFE",
      grey20: "#dddce5",
      grey30: "#BDBBCA",
      grey40: "#7e848b",
      grey50: "#373c4b",
      grey60: "#373c4b",
      grey80: "#1e222c",
      grey100: "#181c20",
      accent: "#077BFF",
    },
    space: {
      0: "0px",
      px: "1px",
      semi: "2px",
      1: "4px",
      2: "8px",
      3: "12px",
      4: "16px",
      5: "20px",
      6: "24px",
      8: "32px",
      10: "40px",
      12: "48px",
      16: "64px",
      20: "80px",
      28: "96px",
    },
    sizes: {
      0: "0px",
      px: "1px",
      semi: "2px",
      1: "4px",
      2: "8px",
      3: "16px",
      4: "20px",
      5: "24px",
      6: "32px",
      7: "42px",
      8: "64px",
      9: "80px",
      10: "96px",
    },
    fontSizes: {
      1: "12px",
      2: "13px",
      3: "15px",
    },
    fonts: {
      untitled: '"Averta PE", apple-system, system-ui sans-serif',
      mono: "iA Writer Mono S, monospace-ui, monospace",
    },
  },
  media: {
    xs: "(min-width: 375px)",
    sm: "(min-width: 540px)",
    md: "(min-width: 960px)",
    lg: "(min-width: 128px)",
    xl: "(min-width: 1600px)",
  },
});
